# Generated by Django 4.0.3 on 2023-02-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_siteselector_originsite_site_selector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteselector',
            name='image_selector_css',
            field=models.TextField(blank=True, null=True, verbose_name='Selektor obrazu css'),
        ),
        migrations.AlterField(
            model_name='siteselector',
            name='image_selector_xpath',
            field=models.TextField(blank=True, null=True, verbose_name='Selektor obrazu xpath'),
        ),
        migrations.AlterField(
            model_name='siteselector',
            name='price_selector_css',
            field=models.TextField(blank=True, null=True, verbose_name='Selektor cen css'),
        ),
        migrations.AlterField(
            model_name='siteselector',
            name='price_selector_xpath',
            field=models.TextField(blank=True, null=True, verbose_name='Selektor cen xpath'),
        ),
    ]
