# Generated by Django 4.0.3 on 2023-02-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_alter_siteselector_image_selector_css_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='originsite',
            name='scraping_engine',
            field=models.CharField(choices=[('P', 'PLAYWRIGHT'), ('R', 'REQUESTS_HTML')], default='R', max_length=32),
        ),
    ]
